@startuml ユースケース図
' left to right direction
skinparam actorStyle awesome
actor 利用者 #pink;line:red;line.bold;text:red
package 携帯システム {
usecase 連絡先を登録する
usecase 電話をかける
}
利用者 --> 連絡先を登録する
利用者 --> 電話をかける
@enduml
