@startuml 例題3
left to right direction
actor 利用者 as user #DDDDDD;line:black;line.bold;
actor 管理者 as atomic #DDDDDD;line:black;line.bold;
rectangle 図書館システム {
usecase ユーザを登録する as T << U1 >>
usecase ユーザを認証する << U2 >>
usecase 図書を検索する << U3 >>
usecase 貸出をうける << U4 >>
}
user----> T:<< 登録 >>
user----> ユーザを認証する:<< 認証 >>
user----> 図書を検索する:<< 検索 >>
user----> 貸出をうける:<< 貸出 >>
T <---- atomic:<< 登録 >>
貸出をうける <---- atomic:<< 貸出 >>
@enduml