@startuml 従業員登録システム
left to right direction
actor 人事担当者 #DDDDDD;line:black;line.bold;
actor 社員 #DDDDDD;line:black;line.bold;
rectangle 従業員登録システム {
usecase 従業員システムを変更する
usecase 従業員システムを登録する
usecase 社員情報を参照する
}
人事担当者 --> 従業員システムを変更する
人事担当者 --> 従業員システムを登録する
社員 --> 社員情報を参照する
@enduml
