@startuml 演習6-5-1
left to right direction
class ライントレーサー{}
class 光センサー{}
class 右モーター{}
class 左モーター{}
class CPU{}
class 電源SW{}
ライントレーサー "1" *--"1"右モーター
ライントレーサー "1" *--"1"光センサー
ライントレーサー  "1" *--"1"左モーター
ライントレーサー  "1" *--"1"CPU
ライントレーサー  "1" *--"1"電源SW
@enduml