@startuml
left to right direction

class 注文詳細{
    合計
    }
class 注文{
    数量
    小計
}
class 割引クーポン{
    値引額
    期限
}
class 商品{
    名称
    単価
}
class ドリンク{
    種別
}
class カップ{
    サイズ
}
class フード{}


class 材料{}
class ポテト{
    サイズ
}
class レシピ{
    種別
}
class ハンバーガー{}
class パン{}
class 肉{}
class 野菜{}
class チーズ{}

注文詳細"1" o--"*"注文
注文"0..*"--"0..1"割引クーポン
注文"0..*"-down-"1"商品
ドリンク--|>商品
カップ"1..3"--"0..*"ドリンク
フード--|>商品
材料"1"--"1"フード
ポテト--|>フード
レシピ--|>フード
ハンバーガー"1..*"--o "1..*"レシピ
パン--|>ハンバーガー
肉--|>ハンバーガー
野菜--|>ハンバーガー
チーズ--|>ハンバーガー
@enduml