@startuml ホテル予約システム
    left to right direction
        actor 利用者 #DDDDDD;line:black;line.bold;
        actor 管理者 #DDDDDD;line:black;line.bold;
        actor 従業員 #DDDDDD;line:black;line.bold;
    rectangle ホテル予約システム {
    usecase 会員登録
    usecase キャンペーン
    usecase 空室状況閲覧
    usecase (<u>予約</u>\n拡張点\nキャンペーン期間\n会員登録) as input
    usecase 予約集計
    usecase 空室状況
    usecase ログイン
    }
    利用者 --> 会員登録
    利用者 --> 空室状況閲覧
    会員登録 .> input : <<extend>>
    キャンペーン .> input : <<extend>>
    input .> ログイン : <<extend>>
    予約集計 .> ログイン : << include >>
    空室状況 .> ログイン : << include >>
    管理者 --> 予約集計
    従業員 <|-- 管理者
    従業員 --> 空室状況
@enduml
