@startuml
title 7-2
|顧客|
|スタッフ|
|厨房|
|スタッフ|
start
:挨拶をする;
:注文を聞く;
|顧客|
:注文する;
|スタッフ|
:注文を確認する;
fork
:代金を請求する;
|顧客|
:代金を支払う;
|スタッフ|
:清算する;
fork again
:商品の調理を依頼する;
|厨房|
:商品を料理する;
|スタッフ|
end fork
:テイクアウトかどうか尋ねる;
if() is (テイクアウト) then
:袋に詰める;
else(店内)
:トレイに乗せる;
endif
:商品を渡す;
|顧客|
:商品を受け取る;
stop
@enduml