@startuml 演習6-3-2
left to right direction
[*] --> メニュー: 接続
メニュー--> [*]: 切断

メニュー-->予約と確認: 予約と確認を選択する
予約と確認-->メニュー: 取消ボタンを押す

予約と確認-->あなたの順番: 登録ボタンを押す
予約と確認-->あなたの順番: 確認ボタンを押す
あなたの順番-->メニュー: メニューへボタンを押す
メニュー--> 今の順番: 今の順番ボタンを押す
今の順番--> メニュー: メニューへボタンを押す

@enduml