@startuml 演習2-1
left to right direction
actor 申請者#DDDDDD;line:black;line.bold;
actor 認証者#DDDDDD;line:black;line.bold;
actor 経理担当者#DDDDDD;line:black;line.bold;
actor 交通費精算システム#DDDDDD;line:black;line.bold;
rectangle 出張申請システム {
usecase 出張申請を登録する
usecase 出張申請を提出する
usecase 出張申請を承認する
usecase 出張申請を却下する
usecase 出張申請を差し出す 
usecase 出張申請を確認する
}
申請者--> 出張申請を登録する
申請者--> 出張申請を提出する
認証者--> 出張申請を承認する
認証者--> 出張申請を却下する
認証者--> 出張申請を差し出す
経理担当者--> 出張申請を確認する
出張申請を登録する <-- 交通費精算システム
@enduml
