@startuml 演習6-3-2
left to right direction
[*] --> メニュー画面
メニュー画面--> 予約と確認画面: 予約と確認ボタンを押す
予約と確認画面--> 貴方の順番画面: 登録ボタンを押す
予約と確認画面-->貴方の順番画面: 確認ボタンを押す
メニュー画面<--予約と確認画面: 取り消しボタンを押す
メニュー画面-->今の番号: 今の順番ボタンを押す
メニュー画面<--貴方の順番画面: メニューボタンを押す
メニュー画面<--今の番号: メニューボタンを押す
メニュー画面--> [*]
@enduml