@startuml
left to right direction
class 利用者{
    -名前
    -住所
    -電話番号
}
class ホテル{
    -部屋
}
class 部屋{
    -タイプ
    -価格
    -キャンペーン価格
}
class 予約{
    -チェックイン日
    -滞在期間
    -値段
}
ホテル "1" *-- "*" 部屋
ホテル "1" -- "*" 利用者 : 登録 <
予約 "*" -- "1" ホテル 
予約 "1" o-- "*" 利用者
予約 "1" -- "1" 部屋
@enduml