@startuml ユースケース図
actor 利用者
rectangle ホテル宿泊予約 {
usecase キャンペーン
usecase ログイン
usecase (<u>予約</u>\n拡張点\nキャンペーン期間) as input
}
利用者 --> input
input <. (キャンペーン) : <<extend>>
ログイン <. input : << include >>
@enduml
