@startuml
hide footbox
Actor ":会員" as a1
participant ":注文登録画面" as a2 <<boundary>>
participant ":商品" as a3 <<entity>>
participant ":注文" as a4 <<entity>>
activate a1
a1->a2
    activate a2
       
    a2->a3:商品情報確認()
    activate a3
    a3-->a2:商品情報取得（）
     deactivate a3
    a2->a2:商品情報表示（商品情報）
     activate a2
     deactivate a2
    deactivate a2
    a1->a2:
    activate a2
    create a4
    a2->a4:<<create>>
   
@enduml